# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
# Merging `spec.env` by name relies on the merge key in the generated Kustomize OpenAPI
# document (added by ai-dynamo/dynamo#15064). Without it kustomize treats `spec.env` as
# an atomic list and this patch would REPLACE the base environment rather than add to
# it, silently dropping MODEL_NAME and HF_HOME. `render --check` catches that, so do not
# regenerate this manifest on a branch that predates #15064.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
patches:
  - target:
      group: nvidia.com
      version: v1beta1
      kind: DynamoGraphDeployment
      name: k-exaone-2-disagg
    path: patch-dgd.yaml
